name: GitHub Environmen1

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    environment: Self

    steps:
      - name: 'Print secret from environment'
        run: |
          echo "APP_SECRET: ${{ secrets.APP_SECRET }}"
